CREATE TABLE utilisateur(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_name VARCHAR(50) NOT NULL UNIQUE,
   lastname VARCHAR(50) NOT NULL,
   password VARCHAR(255) NOT NULL
);


CREATE TABLE Reservation(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   
date_reservation TIMESTAMP,
date_de_visite DATE,
prix VARCHAR(50),
Id_User INT NOT NULL,
   PRIMARY KEY(Id_Reservation),
   FOREIGN KEY(Id_User) REFERENCES utilisateur(Id_User)
);




select * from reservation;
CREATE TABLE Dinosaures (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Regime VARCHAR(50) NOT NULL,
    Name_ VARCHAR(50) NOT NULL,
dino_description TEXT NOT NULL
);
SELECT * from dinosaures;

CREATE TABLE Type_billet(
   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   prix INT NOT NULL,
   quantiter INT,
   PRIMARY KEY(Id_Type_billet)
);

INSERT INTO type_billet (name, prix, quantiter)
VALUES
('Adulte', 20.00, 100),
('Enfant', 10.00, 200),
('VIP', 50.00, 20);

CREATE TABLE proposer(
   Id_Reservation INT,
   Id_Type_billet INT,
   PRIMARY KEY(Id_Reservation, Id_Type_billet),
   FOREIGN KEY(Id_Reservation) REFERENCES Reservation(Id_Reservation),
   FOREIGN KEY(Id_Type_billet) REFERENCES Type_billet(Id_Type_billet)
);
SELECT * from proposer;
CREATE TABLE autoriser(
   Id_Dinosaures INT,
   Id_Type_billet INT,
   PRIMARY KEY(Id_Dinosaures, Id_Type_billet),
   FOREIGN KEY(Id_Dinosaures) REFERENCES Dinosaures(Id_Dinosaures),
   FOREIGN KEY(Id_Type_billet) REFERENCES Type_billet(Id_Type_billet)
);

INSERT INTO autoriser (id_dinosaures, id_type_billet)
VALUES 
(1, 1),
(2, 1),
(3,1),
(4,1),
(8,1),
(9,1),
(10,1),
(16,1),
(17,1),
(18,1),
(5,2),
(6,2),
(7,2),
(15,2),
(20,2),
(11,3),
(12,3),
(13,3),
(14,3),
(19,3);

